sudo: required
services:
- docker
language: bash
script:
# build image
- ./build.sh
# test image
- ./test.sh
# push image
- >
  if [ ! -z "$TRAVIS_TAG"  ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    ./deploy.sh
  fi
